import localFont from "next/font/local";
import "./globals.css";

const gemufDemoSans = localFont({
  src: "./fonts/GemufDemoRegular.ttf",
  variable: "--font-gemuf-demo",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gemufDemoSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
